import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline, ThemeProvider, createTheme } from "@mui/material";
import theme from "../utils/theme/index";
import ThemeRegistry from "./ThemeRegistory";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const darkTheme = createTheme({
//   palette: {
//     mode: "dark",
//   },
// });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <ThemeProvider theme={darkTheme}>
//         <CssBaseline />
//         <body className={inter.className}>{children}</body>
//       </ThemeProvider>
//     </html>
//   );

// }

export default function RootLayout(props: { children: any }) {
  const { children } = props;
  return (
    <html lang="ja">
      <body>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
